### ISSUE TITLE
Re-issue credentials

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#229] opened 2021-11-03 20:23 UTC
# API Services Portal Issue

## User Story

**As a** Developer,<br>
**I want** to be able to recreate my credentials<br>
**so that** I can use them to access APIs that I already have access to, without having to wait for another access approval.

### ENV

- [ ] `DEV`
- [ ] `TEST`
- [ ] `PROD`

### TESTCASE

- Go to "My Access"
- Find the API that you want to regenerate credentials for
- Select "Generate New Credentials"
- Collect the new credentials

### EXPECTED

- New credentials are displayed and ready to use
- Old credentials are revoked

**Comment by elisafw-ux** [comment] 2022-03-15 21:33
duplicate of #332. closed issue.

**Closed by elisafw-ux** 2022-03-15 21:33 UTC
Labels: enhancement, ui, UX/UI
