### ISSUE TITLE
My Access page giving a 500 error

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#161] opened 2021-07-30 22:45 UTC
When I log in with my Github account and go to My Access in Test environment, I get this page:

![Screen Shot 2021-07-30 at 3.45.52 PM.png](https://images.zenhubusercontent.com/5c3e5c85cff96b450939aec6/d226de3c-1c20-4e20-bf4c-befd54cbc4b5)

**Comment by ikethecoder** [comment] 2021-07-30 22:47
In the logs, I get this, but no other details:

```
TypeError: Cannot read property 'id' of null
    at /app/dist/www/server/pages/devportal/access.js:2582:145
    at arrayAggregator (/app/node_modules/lodash/_arrayAggregator.js:17:32)
    at /app/node_modules/lodash/_createAggregator.js:19:12
    at AccessList (/app/dist/www/server/pages/devportal/access.js:2579:41)
```

**Comment by ikethecoder** [comment] 2021-07-30 23:00
I think the issue is that there are ServiceAccess records with no ProductEnvironment, which in theory should not happen.

Why would there be records for:
```
select * from "ServiceAccess" where "productEnvironment" is null;
```

**Comment by Jonesy** [comment] 2021-07-30 23:19
This might be a duplicate of #148, where I have added some filtering for if these sneak by the API.

**Comment by ikethecoder** [comment] 2021-07-30 23:25
Root cause is that it is possible to get orphaned Environments (Environments that are not associated with any Products).  This can occur when Products and Environments are updated via the Directory API.

This ticket will cleanup the orphaned records:
```
select * from "Environment" where product is null;
```

And will fix the Directory API (Batch Feeder) to avoid such issues in the future.

**Comment by ikethecoder** [comment] 2022-02-24 19:32
This error can also occur when an Environment is deleted.  In this case, existing ServiceAccess records get there `productEnvironment` attribute set to `null`.

**Closed** 2022-03-22 06:33 UTC
Labels: bug
