### ISSUE TITLE
Portal General Notice Banner

### ISSUE THREAD

**Issue by jTendeck** [bcgov/api-services-portal#928] opened 2023-10-04 19:19 UTC
As an APS user, I would like to be informed of any issues with the portal/gateway from the portal, so that I may be better aware of issues affecting these services.

During the [Oct 4 Silver Outage](https://chat.developer.gov.bc.ca/channel/devops-alerts?msg=fTmNWByEPGaHqEoSJ), it would have been useful to provide notice to clients using the portal that the gateway in Silver was not available. While we do have a maintenance banner, the outage with the gateway did not stem from maintenance. Additionally, the portal was still functional; only the gateway was experiencing issues.

**Comment by ikethecoder** [comment] 2023-10-24 15:37
Needs some UX for showing how this banner is displayed on the Portal.

**Comment by ikethecoder** [comment] 2023-10-24 15:49
Duplicate of #288, closing

**Closed** 2023-10-24 15:50 UTC
Labels: ux
